services:
  localstack:
    container_name: sandbox_siege_localstack
    image: localstack/localstack:3.8.1
    ports:
      - "4566:4566"            # LocalStack Gateway & Edge Proxy
      - "127.0.0.1:4510-4559:4510-4559"  # External service ports
    environment:
      - LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT=1
      - DEBUG=1
      - PERSISTENCE=1
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3,dynamodb,sqs,sns,iam,lambda
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./data:/var/lib/localstack"
      - "./init-scripts:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - siege_network

networks:
  siege_network:
    driver: bridge
